### ISSUE TITLE
signOut error case crash

### ISSUE THREAD

**Issue by chrisribe** [chrisribe/ti-firebase#2]
I set the code in the signOut method to only return a simple error string.
The generated NSError seems to crash my app if I do anything with it.

https://github.com/chrisribe/ti-firebase/blob/master/iphone/Classes/TiFirebaseModule.m#L248

**Comment by hansemannn** [comment]
Fixed as part of https://github.com/chrisribe/ti-firebase/pull/6

**Comment by chrisribe** [comment]
The error still occurs, I tried to debug the issue. But as soon as I touch the error var the app crashes, "[objc_msgSend](http://www.sealiesoftware.com/blog/archive/2008/09/22/objc_explain_So_you_crashed_in_objc_msgSend.html)".

Commented the callback code in master and replaced with error string.

**Comment by chrisribe** [comment]
Ok found code snip on the web and now using bool result and not crashing.
https://github.com/chrisribe/ti-firebase/blob/master/iphone/Classes/TiFirebaseAuthModule.m#L128

Cannot seem to cause and error signOut always succeeds so, marking as fixed for now.
